---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aap-chatbot-config
data:
  aapconfig.yaml: |
    llm_providers:
      - name: my_rhoai
        type: rhoai_vllm
        # url: "https://granite-8b.wisdom-model-staging.svc.cluster.local/v1"
        url: "https://7f09-104-148-219-166.ngrok-free.app/v1"
        models:
          - name: granite-8b
    ols_config:
      reference_content:
        # product_docs_index_path: "./vector_db/aap_product_docs/2.5"
        # product_docs_index_id: aap-product-docs-2_5
        # embeddings_model_path: "./embeddings_model"
      conversation_cache:
        type: memory
        memory:
          max_entries: 1000
      logging_config:
        app_log_level: info
        lib_log_level: warning
        uvicorn_log_level: info
      default_provider: my_rhoai
      default_model: granite-8b
      query_validation_method: llm
      user_data_collection:
        feedback_disabled: false
        feedback_storage: "/tmp/data/feedback"
        transcripts_disabled: false
        transcripts_storage: "/tmp/data/transcripts"
    dev_config:
      # config options specific to dev environment - launching OLS in local
      enable_dev_ui: false
      disable_auth: true
      disable_tls: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-chatbot
  template:
    metadata:
      labels:
        app: ansible-chatbot
    spec:
      imagePullSecrets:
        - name: quay-pull-secret
      volumes:
        - name: aap-chatbot-config
          configMap:
            name: aap-chatbot-config
      containers:
        - name: ansible-chatbot
          image: quay.io/ansible/ansible-chatbot-service:61be2d6cc53f0c6d2f9783f636d347348ef13419
          env:
            - name: OLS_CONFIG_FILE
              value: /app-root/aapconfig.yaml
            - name: OPENAI_API_KEY
              value: dummy
          volumeMounts:
            - name: aap-chatbot-config
              mountPath: /app-root/aapconfig.yaml
              subPath: aapconfig.yaml

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ansible-chatbot-service
  name: ansible-chatbot-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ansible-chatbot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
